### ISSUE TITLE
Async initializer

### ISSUE THREAD

**Issue by haiduong87** [neosmart/AspSqliteCache#2]
Hello @mqudsi 

Can we have a new version that use async initializer?

Thank you!

haiduong87

**Comment by mqudsi** [comment]
I'll start with saying that all the code for async initialization is already in the repo pretty much from the start, disabled while waiting on Microsoft to add async initializer support to ASP.NET Core.

That said, can I ask what value you think there is in using async initialization for the ASP SQLite cache? It's a one-time process, at startup, independent of load or number of connections; e.g. not very interesting from an async init perspective.

**Comment by haiduong87** [comment]
Hi @mqudsi ,

Thanks for the explanation about the cache initialization.

I just create this issue because I see those lines about the async initialization. 
Actually I tried to do it locally, but I don't know much about the caching logic.

So we can happy with the current state :D

Thank you!

**Comment by mqudsi** [comment]
No problem! Glad I could help shed light on your question. Generally async is used to maximize throughout or minimize latency for routines that are requested at high frequency or in large quantity. Due to the nature of async, anything that would block the async request should also be made async, but per-process init generally doesn’t fall into that category. 

Now if, for the sake of example, you were creating a new SQLite cache instance per request (rather than per app), then you would definitely want some sort of async initialized, but of course you would never want a cache to be created per request as that defeats its purpose altogether.
